---

root: true

env:
  es6: true
  browser: true
  mocha: true
  node: true

rules:
  indent: [2, tab]
  no-console: 0
  curly: [2, all]
  object-curly-spacing: [2, never]
  space-before-function-paren: [2, never]
  space-in-parens: [2, never]
  space-infix-ops: 2
  space-before-blocks: 2
  spaced-comment: [2, always]
  strict: 0 
  no-unused-vars: 0
  no-undef: 0

globals:
  log: false

extends: eslint:recommended
